/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                'neon-cyan': 'var(--primary)',
                'neon-magenta': 'var(--accent)',
                'neon-violet': 'var(--secondary)',
                'dark-bg': 'var(--bg-color)',
                'card-bg': 'var(--card-bg)',
                'text-primary': 'var(--text-primary)',
                'text-secondary': 'var(--text-secondary)',
                'badge-bg': 'var(--badge-bg)',
                'badge-border': 'var(--badge-border)',
                'button-bg': 'var(--button-bg)',
                'button-border': 'var(--button-border)',
                'button-hover-bg': 'var(--button-hover-bg)',
                'section-bg': 'var(--section-bg)',
                'metric-bg': 'var(--metric-bg)',
                'metric-border': 'var(--metric-border)',
                'metric-text': 'var(--metric-text)',
                'tag-bg': 'var(--tag-bg)',
                'tag-border': 'var(--tag-border)',
                'divider-border': 'var(--divider-border)',
                'card-placeholder-bg': 'var(--card-placeholder-bg)',
                'card-placeholder-icon': 'var(--card-placeholder-icon)',
                'timeline-border': 'var(--timeline-border)',
                'icon-bg': 'var(--icon-bg)',
                'icon-color': 'var(--icon-color)',
                'input-bg': 'var(--input-bg)',
                'input-border': 'var(--input-border)',
                'footer-bg': 'var(--footer-bg)',
                'footer-border-top': 'var(--footer-border-top)',
            },
            fontFamily: {
                sans: ['Inter', 'sans-serif'],
                display: ['Poppins', 'sans-serif'],
            },
            animation: {
                'spin-slow': 'spin 20s linear infinite',
                'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
            },
        },
    },
    plugins: [],
}
